👷 Add step for checking if Python stub files are up to date (#286)
* Add step for checking if Python stub files are up to date

* Stub-generation script should not fail job

* Show diff on failure

* Update changelop and upgrade guide

* Apply suggestion from @burgholzer

Co-authored-by: Lukas Burgholzer <burgholzer@me.com>
Signed-off-by: Daniel Haag <121057143+denialhaag@users.noreply.github.com>

* Check if the stub-generation script exists

* Streamline error message

---------

Signed-off-by: Daniel Haag <121057143+denialhaag@users.noreply.github.com>
Co-authored-by: Lukas Burgholzer <burgholzer@me.com>

diff --git a/.github/workflows/reusable-python-linter.yml b/.github/workflows/reusable-python-linter.yml
--- a/.github/workflows/reusable-python-linter.yml
+++ b/.github/workflows/reusable-python-linter.yml
@@ -34,6 +34,10 @@ on:
         description: "The LLVM version to set up (formatted as 'major.minor.patch') or commit hash (minimum 7 characters, e.g., 'a832a52')"
         default: "21.1.7"
         type: string
+      check-stubs:
+        description: "Whether to check if the stub files are up to date. Requires 'bindings/generate-stubs.sh' to exist"
+        default: false
+        type: boolean
 
 jobs:
   lint:
@@ -63,6 +67,20 @@ jobs:
         with:
           enable-cache: true
           save-cache: ${{ github.ref == 'refs/heads/main' }}
+
+      - name: Check if stub files are up to date
+        if: ${{ inputs.check-stubs }}
+        run: |
+          if [[ ! -f ./bindings/generate-stubs.sh ]]; then
+            echo "'./bindings/generate-stubs.sh' not found. Please disable the 'check-stubs' input or create a stub-generation script."
+            exit 1
+          fi
+          ./bindings/generate-stubs.sh || true
+          if [[ $(git status --porcelain python) ]]; then
+            echo "Stub files are not up to date. Please run './bindings/generate-stubs.sh' and commit the changes."
+            git --no-pager diff python
+            exit 1
+          fi
 
       # run mypy for static type checking
       - name: Run mypy
